### ISSUE TITLE
panic in example at rng.gen_range

### ISSUE THREAD

**Issue by iancoleman** [maidsafe/parsec#312] opened 2019-05-30 04:31 UTC
The basic example will sometimes panic.

```
cargo run --release --example=basic --features=mock -- --initial-peers=20 --opaque=10 --seed=4138645876,637453496,194668239,3557059928
```
ends after round 120 with

```
thread 'main' panicked at 'Rng.gen_range called with low >= high', /home/ian/.cargo/registry/src/github.com-1ecc6299db9ec823/rand-0.4.2/src/lib.rs:519:9
```

Probable source for fix:

Related to
https://rust-random.github.io/rand/rand/trait.Rng.html#panics
and happens at
https://github.com/maidsafe/parsec/blob/8c0d9d00e8027f8c8212b4ad03c6ffadc3f22252/examples/basic.rs#L504
where the second term is problematic

**Comment by pierrechevalier83** [comment] 2019-06-03 16:34
Thanks a lot for the report @iancoleman :smile: 

The panick itself can easily be fixed by avoiding calling `gen_range(1, 1)`, returning `1` instead in that special case. We do get stuck, though with this seed and that change.

I started exploring this and got some observations:

We can reproduce it with a slightly smaller example:
```
cargo run --release --example=basic --features=mock -- --initial-peers=16 --opaque=0 --seed=4138645876,637453496,194668239,3557059928 --add-peers 0 --remove-peers 1
```
16 peers, 1 to remove, 0 to add, no opaque observations.

What happens in this case is that 16 nodes actually attempt to remove 13 nodes.
At the end, `Fred` doesn't seem to be participating anymore and `Alice` and `Kent` are stuck forever trying to remove `Fred`. This makes sense since they're only `2` out of `3` which is less than a supermajority.

I'm not sure exactly what we expect, but I am surprised in a  first place that we try to remove so many nodes with the `remove-peers 1` parameter.

@Fraser999, maybe you will remember better than me what we're aiming for in this example.

**Closed** 2019-06-10 10:11 UTC
